name: sputnik_di
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  meta: ^1.12.0
  rxdart: ^0.28.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
