name: sputnik_di
description: 'Lightweight Dependency Injection Framework for your Flutter project'
version: 0.0.2
repository: https://github.com/WebMad/sputnik_di/tree/main/packages/sputnik_di

topics:
  - dependency-injection
  - inversion-of-control
  - ioc
  - container
  - utils

funding:
  - 'https://boosty.to/gubin-dev/donate'

environment:
  sdk: '>=3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  meta: ^1.12.0
  rxdart: ^0.28.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
