name: sputnik_di
description: Lightweight DI for your Dart project
version: 0.0.1
repository: https://github.com/WebMad/sputnik_di/tree/main/packages/sputnik_di

environment:
  sdk: '>=3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  meta: ^1.12.0
  rxdart: ^0.28.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
