name: flutter_sputnik_di
description: 'Lightweight Dependency Injection Framework for your Flutter project'
version: 0.0.2
repository: https://github.com/WebMad/sputnik_di/tree/main/packages/flutter_sputnik_di

topics:
  - dependency-injection
  - inversion-of-control
  - ioc
  - container
  - utils

funding:
  - 'https://boosty.to/gubin-dev/donate'

environment:
  sdk: '>=3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  nested: ^1.0.0
  sputnik_di: ^0.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
