name: flutter_sputnik_di
description: Lightweight DI for your Flutter project
version: 0.0.1
repository: https://github.com/WebMad/sputnik_di/tree/main/packages/flutter_sputnik_di

environment:
  sdk: '>=3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  nested: ^1.0.0
  sputnik_di: ^0.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
